version: '3'
services:
  registry:
    image: public.ecr.aws/d8i9k4x3/fso-lab-teastore-registry
    expose:
      - "8080"
  db:
    image: public.ecr.aws/d8i9k4x3/fso-lab-teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"
  persistence:
    image: public.ecr.aws/d8i9k4x3/fso-lab-teastore-persistence
    expose:
      - "8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
  auth:
    image: public.ecr.aws/d8i9k4x3/fso-lab-teastore-auth
    expose:
      - "8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
  image:
    image: public.ecr.aws/d8i9k4x3/fso-lab-teastore-image
    expose:
      - "8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
  recommender:
    image: public.ecr.aws/d8i9k4x3/fso-lab-teastore-recommender
    expose:
      - "8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
  webui:
    image: public.ecr.aws/d8i9k4x3/fso-lab-teastore-webui
    expose:
      - "8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
    ports:
      - "8080:8080"
  orderprocessor:
    image: public.ecr.aws/d8i9k4x3/fso-lab-teastore-orderprocessor
    environment:
      HOST_NAME: "orderprocessor"
      REGISTRY_HOST: "registry"
      MEM_INCREMENT_MB: 10
      PROCESSING_RATE_SECONDS: 30
    depends_on:
      - persistence
      - registry
    mem_limit: 512M