apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-ldap
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-ldap
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-ldap
    spec:
      containers:
        - name: teastore-ldap
          image: public.ecr.aws/d8i9k4x3/fso-lab-teastore-ldap
          ports:
            - containerPort: 8888
            - containerPort: 1389
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-ldap
  labels:
    app: teastore
    run: teastore-ldap
spec:
  ports:
    - port: 8888
      protocol: TCP
      name: reverse-shell
    - port: 1389
      protocol: TCP
      name: ldap
  selector:
    run: teastore-ldap
---
