apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-image
  labels:
    framework: java
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-image
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-image
    spec:
      containers:
        - name: teastore-image
          image: public.ecr.aws/d8i9k4x3/fso-lab-teastore-image
          ports:
            - containerPort: 8080
          env:
            - name: HOST_NAME
              value: "teastore-image"
            - name: REGISTRY_HOST
              value: "$REGISTRY_NODEPORT_HOST"
            - name: REGISTRY_PORT
              value: "$REGISTRY_NODEPORT_PORT"
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-image
  labels:
    app: teastore
    run: teastore-image
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: teastore-image
---
